### PR TITLE
Add more transitive dependencies

### PR DESCRIPTION
**Pull request by ZheSun88**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker-flow/5)

### CODE REVIEW

**Review by denis-anisimov — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker-flow/5)* status: all files reviewed, 1 unresolved discussion (waiting on @denis-anisimov and @ZheSun88)

*[a discussion](https://reviewable.io/reviews/vaadin/vaadin-time-picker-flow/5#-LJDChyo1UMB070G-43N:-LJDChyo1UMB070G-43O:b-cb86wf) (no related file):*
Could you please comment what's the reason of explicit transitive dependencies ?

---

**Review by ZheSun88 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker-flow/5)* status: all files reviewed, 1 unresolved discussion (waiting on @denis-anisimov)

*[a discussion](https://reviewable.io/reviews/vaadin/vaadin-time-picker-flow/5#-LJDChyo1UMB070G-43N:-LJDr09xAeEMwuEbFDkX:b-16euji) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Could you please comment what's the reason of explicit transitive dependencies ?
</blockquote></details>

That is the same idea like all the other flow components. via setting the transitive dependencies explicitly, we can be sure that they are all using the same and pinned version as it is in the `flow-component-base`. Otherwise, it might be finding a version which fits it range. 
That is my understanding. theoretically, we dont need to do this, but last week, we have found some versions of webcomponents are used accidentally, which caused some build failure. 

---

**Review by denis-anisimov — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker-flow/5#-:-LJED7r61efwCHwdng7E:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @denis-anisimov)

**Review by denis-anisimov — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker-flow/5)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
