### PR TITLE
Allow null values for setValue() in TimePicker

### PR DESCRIPTION
**Pull request by svipal**
This came up :

This commit breaks the feature of setting NULL values in timepicker:

``` 
public void setValue(LocalTime value) {
    	LocalTime truncated_value = value.truncatedTo(ChronoUnit.MILLIS);
    	super.setValue(truncated_value);
}
```

[https://github.com/vaadin/vaadin-time-picker-flow/commit/e1b3a2fc6cd5e1a213a60969e43bf90f3047383f#diff-242f4700b1a3ce7b94bf2092fb36ad88](url)

_Originally posted by @ThijsMaenhout in https://github.com/vaadin/vaadin-time-picker-flow/pull/28#issuecomment-478868036_

This is a fix for that.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker-flow/30)

### CODE REVIEW

**Review by pleku — CHANGES_REQUESTED** [review]
It was my bad for letting the previous change in without a test, and also completely forgot the `null` case.

Please add a unit test that verifies that time picker does accept null values, there should have been one from the start. To here: https://github.com/vaadin/vaadin-time-picker-flow/blob/master/vaadin-time-picker-flow/src/test/java/com/vaadin/flow/component/timepicker/tests/TimePickerTest.java

**Comment by pleku** [comment]
Also, the code doesn't even compile because it is missing one ";"

**Comment by pleku** [comment]
Also this commit should be made on top of an update from `master` branch or a fresh fork. Now there are conflicts

**Comment by svipal** [comment]
Holy moly.

**Pull request closed without merging**
