### PR TITLE
Refactor the project into multiple modules

### PR DESCRIPTION
**Pull request by pleku**
Pins webjar versions in component project. Updates versions to most latest ones (except vaadin-text-field).
Uses Flow 1.3-SNAPSHOT and component-base 1.3.0-SNAPSHOT.
Adds TestBench Element API and refactores ITs to use that.
Bumps version to 1.1-SNAPSHOT

Part of vaadin/flow-component-base#117

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker-flow/14)

### CODE REVIEW

**Comment by pleku** [comment]
Do not squash commits when merging!

**Review by pleku — COMMENTED** [review]
> Dismissed @vaadin-bot from 18 discussions.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker-flow/14)* status: 0 of 17 files reviewed, all discussions resolved

**Review by ZheSun88 — CHANGES_REQUESTED** [review]
> Reviewed 11 of 17 files at r1, 4 of 4 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker-flow/14)* status: all files reviewed, 2 unresolved discussions (waiting on @pleku)

___
*[vaadin-time-picker-flow/pom.xml, line 52 at r3](https://reviewable.io/reviews/vaadin/vaadin-time-picker-flow/14#-LX4Dtoo4IxhCPeU1abP:-LX4Dtoo4IxhCPeU1abQ:b-ifjbo6) ([raw file](https://github.com/vaadin/vaadin-time-picker-flow/blob/ea140a8503fbceb35c10eddf62a89a1aace4dbda/vaadin-time-picker-flow/pom.xml#L52)):*
> ```XML
>             <artifactId>vaadin-lumo-styles</artifactId>
>             <version>1.4.0</version>
>         </dependency>
> ```

FYI, the other components are using `vaadin-lumo-styles` `1.3.2`
___
*[vaadin-time-picker-flow/pom.xml, line 187 at r3](https://reviewable.io/reviews/vaadin/vaadin-time-picker-flow/14#-LX4GQUY7uVjqFJ7BkAm:-LX4GQUY7uVjqFJ7BkAn:b-d0wxhj) ([raw file](https://github.com/vaadin/vaadin-time-picker-flow/blob/ea140a8503fbceb35c10eddf62a89a1aace4dbda/vaadin-time-picker-flow/pom.xml#L187)):*
> ```XML
>         </plugins>
>     </build>
> </project>
> ```

new line
___
*[vaadin-time-picker-flow-demo/pom.xml, line 19 at r3](https://reviewable.io/reviews/vaadin/vaadin-time-picker-flow/14#-LX4EKTrAA0DnJeWeJeo:-LX4EKTrAA0DnJeWeJep:blq1s4d) ([raw file](https://github.com/vaadin/vaadin-time-picker-flow/blob/ea140a8503fbceb35c10eddf62a89a1aace4dbda/vaadin-time-picker-flow-demo/pom.xml#L19)):*
> ```
> <flow.version>1.3-SNAPSHOT</flow.version>
> ```

This is not needed, as it has been defined in the parent module
___
*[vaadin-time-picker-flow-demo/pom.xml, line 55 at r3](https://reviewable.io/reviews/vaadin/vaadin-time-picker-flow/14#-LX4EgGY9p2qkD0k-tos:-LX4EgGY9p2qkD0k-tot:buma7an) ([raw file](https://github.com/vaadin/vaadin-time-picker-flow/blob/ea140a8503fbceb35c10eddf62a89a1aace4dbda/vaadin-time-picker-flow-demo/pom.xml#L55)):*
> ```XML
>             <groupId>com.vaadin</groupId>
>             <artifactId>vaadin-combo-box-flow</artifactId>
>             <version>2.0.2</version>
> ```

Should we use a fixed version here? maybe change to a snapshot version
___
*[vaadin-time-picker-flow-integration-tests/pom.xml, line 146 at r3](https://reviewable.io/reviews/vaadin/vaadin-time-picker-flow/14#-LX4G6Nf97A0ul8mnq9u:-LX4G6Nf97A0ul8mnq9v:b-d0wxhj) ([raw file](https://github.com/vaadin/vaadin-time-picker-flow/blob/ea140a8503fbceb35c10eddf62a89a1aace4dbda/vaadin-time-picker-flow-integration-tests/pom.xml#L146)):*
> ```XML
>         </profile>
>     </profiles>
> </project>
> ```

new line
___
*[vaadin-time-picker-flow-testbench/pom.xml, line 46 at r3](https://reviewable.io/reviews/vaadin/vaadin-time-picker-flow/14#-LX4Fx482aRDGE2O7Tgd:-LX4Fx482aRDGE2O7Tge:b-d0wxhj) ([raw file](https://github.com/vaadin/vaadin-time-picker-flow/blob/ea140a8503fbceb35c10eddf62a89a1aace4dbda/vaadin-time-picker-flow-testbench/pom.xml#L46)):*
> ```XML
> 
>     </build>
> </project>
> ```

new line
___
*[vaadin-time-picker-flow-testbench/src/main/java/com/vaadin/flow/component/timepicker/testbench/TimePickerElement.java, line 210 at r3](https://reviewable.io/reviews/vaadin/vaadin-time-picker-flow/14#-LX4FtLN-ZG7NnGQ9Xz6:-LX4FtLN-ZG7NnGQ9Xz7:b-d0wxhj) ([raw file](https://github.com/vaadin/vaadin-time-picker-flow/blob/ea140a8503fbceb35c10eddf62a89a1aace4dbda/vaadin-time-picker-flow-testbench/src/main/java/com/vaadin/flow/component/timepicker/testbench/TimePickerElement.java#L210)):*
> ```Java
>         return getTimePickerTextFieldElement().getValue();
>     }
> }
> ```

new line
___
*[vaadin-time-picker-flow-demo/src/main/java/com/vaadin/flow/component/timepicker/demo/TimePickerView.java, line 31 at r3](https://reviewable.io/reviews/vaadin/vaadin-time-picker-flow/14#-LX4GbtdCJYS4BLGdttS:-LX4GbtdCJYS4BLGdttT:bxo29m9) ([raw file](https://github.com/vaadin/vaadin-time-picker-flow/blob/ea140a8503fbceb35c10eddf62a89a1aace4dbda/vaadin-time-picker-flow-demo/src/main/java/com/vaadin/flow/component/timepicker/demo/TimePickerView.java#L31)):*
> ```Java
> import com.vaadin.flow.component.UI;
> import com.vaadin.flow.component.combobox.ComboBox;
> import com.vaadin.flow.component.html.*;
> ```

I think we have the code convention on not using this kind of import, but we can fix this later

**Review by pleku — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker-flow/14)* status: 11 of 17 files reviewed, 3 unresolved discussions (waiting on @vaadin-bot and @ZheSun88)

___
*[vaadin-time-picker-flow-demo/pom.xml, line 19 at r3](https://reviewable.io/reviews/vaadin/vaadin-time-picker-flow/14#-LX4EKTrAA0DnJeWeJeo:-LXE9f-08u80nGCC9kWL:b-896fix) ([raw file](https://github.com/vaadin/vaadin-time-picker-flow/blob/ea140a8503fbceb35c10eddf62a89a1aace4dbda/vaadin-time-picker-flow-demo/pom.xml#L19)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

> ```
> <flow.version>1.3-SNAPSHOT</flow.version>
> ```

This is not needed, as it has been defined in the parent module
</blockquote></details>

Done.
___
*[vaadin-time-picker-flow-demo/pom.xml, line 55 at r3](https://reviewable.io/reviews/vaadin/vaadin-time-picker-flow/14#-LX4EgGY9p2qkD0k-tos:-LXE9frE7GujVyFoup6k:b-896fix) ([raw file](https://github.com/vaadin/vaadin-time-picker-flow/blob/ea140a8503fbceb35c10eddf62a89a1aace4dbda/vaadin-time-picker-flow-demo/pom.xml#L55)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

Should we use a fixed version here? maybe change to a snapshot version
</blockquote></details>

Done.

**Review by caalador — APPROVED** [review]
> Reviewed 6 of 6 files at r4.
> Dismissed @ZheSun88 from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker-flow/14)* status: all files reviewed, 1 unresolved discussion (waiting on @vaadin-bot)

**Review by caalador — APPROVED** [review]
> Dismissed @vaadin-bot from a discussion.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker-flow/14)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
