### PR TITLE
Initial Implementation of Time Picker

### PR DESCRIPTION
**Pull request by ZheSun88**
#1
Add initial Implementation of the Time Picker;
Add demos and tests.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker-flow/3)

### CODE REVIEW

**Review by ZheSun88 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker-flow/3)* status: 0 of 9 files reviewed, 3 unresolved discussions (waiting on @vaadin-bot)

*[a discussion](https://reviewable.io/reviews/vaadin/vaadin-time-picker-flow/3#-LIjT6GE9j8t2pDsLWW4:-LIjT6GE9j8t2pDsLWW5:b-c6xoun) (no related file):*
there is one missing api to be added

---

**Review by gilberto-torrezan — CHANGES_REQUESTED** [review]
> Reviewed 5 of 9 files at r1, 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker-flow/3)* status: all files reviewed, 11 unresolved discussions (waiting on @vaadin-bot, @gilberto-torrezan, and @ZheSun88)

*[a discussion](https://reviewable.io/reviews/vaadin/vaadin-time-picker-flow/3#-LIjT6GE9j8t2pDsLWW4:-LIkMs2a6NdkrzQm9fJM:b-m9xpwf) (no related file):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

there is one missing api to be added
</blockquote></details>

Which one?

---
*[a discussion](https://reviewable.io/reviews/vaadin/vaadin-time-picker-flow/3#-LIkMtOvBd0JnVtbpqJ4:-LIkMtOvBd0JnVtbpqJ5:bmvu1jc) (no related file):*
Is there no Locale support for this component?

---
___
*[src/main/java/com/vaadin/flow/component/timepicker/TimePicker.java, line 115 at r4](https://reviewable.io/reviews/vaadin/vaadin-time-picker-flow/3#-LIkK6Ko9luvgmZIQ9UZ:-LIkK6Ko9luvgmZIQ9U_:b-pndt6l) ([raw file](https://github.com/vaadin/vaadin-time-picker-flow/blob/b3d1d1a049ee1ce1376cf5dc512a85adfe7fe20e/src/main/java/com/vaadin/flow/component/timepicker/TimePicker.java#L115)):*
> ```Java
>     }
> 
>     @Override
> ```

A better javadoc is needed for this method. The `name` attribute is usually only useful when submitting forms.
___
*[src/main/java/com/vaadin/flow/component/timepicker/TimePicker.java, line 139 at r4](https://reviewable.io/reviews/vaadin/vaadin-time-picker-flow/3#-LIkJK725e90vz9uMb_X:-LIkJK725e90vz9uMb_Y:bvoelpv) ([raw file](https://github.com/vaadin/vaadin-time-picker-flow/blob/b3d1d1a049ee1ce1376cf5dc512a85adfe7fe20e/src/main/java/com/vaadin/flow/component/timepicker/TimePicker.java#L139)):*
> ```Java
>      * @return the current error message
>      */
>     public String getErrorMessage() {
> ```

Needs an `@Override` here as well, since it is inherited from `HasValidation`.
___
*[src/main/java/com/vaadin/flow/component/timepicker/TimePicker.java, line 155 at r4](https://reviewable.io/reviews/vaadin/vaadin-time-picker-flow/3#-LIkJQb_-iFDC_D2UTNy:-LIkJQb_-iFDC_D2UTNz:bvoelpv) ([raw file](https://github.com/vaadin/vaadin-time-picker-flow/blob/b3d1d1a049ee1ce1376cf5dc512a85adfe7fe20e/src/main/java/com/vaadin/flow/component/timepicker/TimePicker.java#L155)):*
> ```Java
>      * @return the {@code validity} property from the time picker
>      */
>     public boolean isInvalid() {
> ```

Needs an `@Override` here as well, since it is inherited from `HasValidation`.
___
*[src/main/java/com/vaadin/flow/component/timepicker/TimePicker.java, line 195 at r4](https://reviewable.io/reviews/vaadin/vaadin-time-picker-flow/3#-LIkLd5l7pvXJpZhymtV:-LIkLd5l7pvXJpZhymtW:b-wtmb0u) ([raw file](https://github.com/vaadin/vaadin-time-picker-flow/blob/b3d1d1a049ee1ce1376cf5dc512a85adfe7fe20e/src/main/java/com/vaadin/flow/component/timepicker/TimePicker.java#L195)):*
> ```Java
> 
>     @Override
>     public void setDisabled(boolean disabled) {
> ```

This should be `setEnabled` instead of `setDisabled`. Implement the `HasEnabled` interface for this.
___
*[src/main/java/com/vaadin/flow/component/timepicker/TimePicker.java, line 206 at r4](https://reviewable.io/reviews/vaadin/vaadin-time-picker-flow/3#-LIkM5e867yMQcZl-SGJ:-LIkM5e867yMQcZl-SGK:b2vqti1) ([raw file](https://github.com/vaadin/vaadin-time-picker-flow/blob/b3d1d1a049ee1ce1376cf5dc512a85adfe7fe20e/src/main/java/com/vaadin/flow/component/timepicker/TimePicker.java#L206)):*
> ```Java
>      * <p>
>      * Specifies the number of valid intervals in a day or in an hour used for
>      * configuring the items displayed in the selection box.
> ```

I know this is copy-pasted from the component, but I can't understand what does it do by just reading the sentence.
___
*[src/main/java/com/vaadin/flow/component/timepicker/TimePicker.java, line 209 at r4](https://reviewable.io/reviews/vaadin/vaadin-time-picker-flow/3#-LIkMBWY5YC42LaCZO1X:-LIkMBWY5YC42LaCZO1Y:b-1yk2ph) ([raw file](https://github.com/vaadin/vaadin-time-picker-flow/blob/b3d1d1a049ee1ce1376cf5dc512a85adfe7fe20e/src/main/java/com/vaadin/flow/component/timepicker/TimePicker.java#L209)):*
> ```Java
>      * </p>
>      * <p>
>      * It also configures the precission of the value string. By default the
> ```

Typo on `precission`
___
*[src/test/java/com/vaadin/flow/component/timepicker/tests/TimePickerValidationPageIT.java, line 24 at r4](https://reviewable.io/reviews/vaadin/vaadin-time-picker-flow/3#-LIkN5Hs2_MQsLWHrydm:-LIkN5Hs2_MQsLWHrydn:b-dnfagc) ([raw file](https://github.com/vaadin/vaadin-time-picker-flow/blob/b3d1d1a049ee1ce1376cf5dc512a85adfe7fe20e/src/test/java/com/vaadin/flow/component/timepicker/tests/TimePickerValidationPageIT.java#L24)):*
> ```Java
> 
> /**
>  * Integration tests for {@link TextField} validation.
> ```

`TextField` validation?

**Review by ZheSun88 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker-flow/3)* status: 7 of 9 files reviewed, 10 unresolved discussions (waiting on @gilberto-torrezan, @vaadin-bot, and @ZheSun88)

*[a discussion](https://reviewable.io/reviews/vaadin/vaadin-time-picker-flow/3#-LIkMtOvBd0JnVtbpqJ4:-LIkNZeA627hq0mFBDiG:b3p5pwd) (no related file):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Is there no Locale support for this component?
</blockquote></details>

there is another ticket for the locale and I18n support. https://github.com/vaadin/vaadin-time-picker-flow/issues/2

---
___
*[src/main/java/com/vaadin/flow/component/timepicker/TimePicker.java, line 115 at r4](https://reviewable.io/reviews/vaadin/vaadin-time-picker-flow/3#-LIkK6Ko9luvgmZIQ9UZ:-LIkQMh_6o3izRmGC87H:b-5vbjop) ([raw file](https://github.com/vaadin/vaadin-time-picker-flow/blob/b3d1d1a049ee1ce1376cf5dc512a85adfe7fe20e/src/main/java/com/vaadin/flow/component/timepicker/TimePicker.java#L115)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

A better javadoc is needed for this method. The `name` attribute is usually only useful when submitting forms.
</blockquote></details>

in this case, should we expose this API here? It looks this method is not added for other componnets, except datepicker.

I am going to remove it, can add it back if necessary.
___
*[src/main/java/com/vaadin/flow/component/timepicker/TimePicker.java, line 139 at r4](https://reviewable.io/reviews/vaadin/vaadin-time-picker-flow/3#-LIkJK725e90vz9uMb_X:-LIkPUdD1Kwg1Lu_V92b:b-896fix) ([raw file](https://github.com/vaadin/vaadin-time-picker-flow/blob/b3d1d1a049ee1ce1376cf5dc512a85adfe7fe20e/src/main/java/com/vaadin/flow/component/timepicker/TimePicker.java#L139)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Needs an `@Override` here as well, since it is inherited from `HasValidation`.
</blockquote></details>

Done.
___
*[src/main/java/com/vaadin/flow/component/timepicker/TimePicker.java, line 155 at r4](https://reviewable.io/reviews/vaadin/vaadin-time-picker-flow/3#-LIkJQb_-iFDC_D2UTNy:-LIkPUMwD4wBOvAI-6Ss:b-896fix) ([raw file](https://github.com/vaadin/vaadin-time-picker-flow/blob/b3d1d1a049ee1ce1376cf5dc512a85adfe7fe20e/src/main/java/com/vaadin/flow/component/timepicker/TimePicker.java#L155)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Needs an `@Override` here as well, since it is inherited from `HasValidation`.
</blockquote></details>

Done.
___
*[src/main/java/com/vaadin/flow/component/timepicker/TimePicker.java, line 195 at r4](https://reviewable.io/reviews/vaadin/vaadin-time-picker-flow/3#-LIkLd5l7pvXJpZhymtV:-LIkOz1d6cCh16aQG5Hy:b-896fix) ([raw file](https://github.com/vaadin/vaadin-time-picker-flow/blob/b3d1d1a049ee1ce1376cf5dc512a85adfe7fe20e/src/main/java/com/vaadin/flow/component/timepicker/TimePicker.java#L195)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

This should be `setEnabled` instead of `setDisabled`. Implement the `HasEnabled` interface for this.
</blockquote></details>

Done.
___
*[src/main/java/com/vaadin/flow/component/timepicker/TimePicker.java, line 206 at r4](https://reviewable.io/reviews/vaadin/vaadin-time-picker-flow/3#-LIkM5e867yMQcZl-SGJ:-LIkTPvg8pIIyXQ9a3gB:b-896fix) ([raw file](https://github.com/vaadin/vaadin-time-picker-flow/blob/b3d1d1a049ee1ce1376cf5dc512a85adfe7fe20e/src/main/java/com/vaadin/flow/component/timepicker/TimePicker.java#L206)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

I know this is copy-pasted from the component, but I can't understand what does it do by just reading the sentence.
</blockquote></details>

Done.
___
*[src/main/java/com/vaadin/flow/component/timepicker/TimePicker.java, line 209 at r4](https://reviewable.io/reviews/vaadin/vaadin-time-picker-flow/3#-LIkMBWY5YC42LaCZO1X:-LIkTkza97WI3nH1RxDk:b-896fix) ([raw file](https://github.com/vaadin/vaadin-time-picker-flow/blob/b3d1d1a049ee1ce1376cf5dc512a85adfe7fe20e/src/main/java/com/vaadin/flow/component/timepicker/TimePicker.java#L209)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Typo on `precission`
</blockquote></details>

Done.
___
*[src/test/java/com/vaadin/flow/component/timepicker/tests/TimePickerValidationPageIT.java, line 24 at r4](https://reviewable.io/reviews/vaadin/vaadin-time-picker-flow/3#-LIkN5Hs2_MQsLWHrydm:-LIkRAL987D09hyuLYfO:b-896fix) ([raw file](https://github.com/vaadin/vaadin-time-picker-flow/blob/b3d1d1a049ee1ce1376cf5dc512a85adfe7fe20e/src/test/java/com/vaadin/flow/component/timepicker/tests/TimePickerValidationPageIT.java#L24)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

`TextField` validation?
</blockquote></details>

Done.

**Review by ZheSun88 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker-flow/3)* status: 7 of 9 files reviewed, 10 unresolved discussions (waiting on @gilberto-torrezan and @vaadin-bot)

*[a discussion](https://reviewable.io/reviews/vaadin/vaadin-time-picker-flow/3#-LIjT6GE9j8t2pDsLWW4:-LIkYyNG0LUWn_v8obzb:b-v9j5b7) (no related file):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Which one?
</blockquote></details>

i was blocking myself for this missing api (setStep) .. now it has been added there, so i resolved this blocking

---

**Review by gilberto-torrezan — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker-flow/3)* status: all files reviewed, 3 unresolved discussions (waiting on @vaadin-bot and @ZheSun88)

___
*[src/test/java/com/vaadin/flow/component/timepicker/tests/TimePickerIT.java, line 63 at r5](https://reviewable.io/reviews/vaadin/vaadin-time-picker-flow/3#-LIo9AXxBoeZi2DniQHs:-LIo9AXxBoeZi2DniQHt:b-9fgcqr) ([raw file](https://github.com/vaadin/vaadin-time-picker-flow/blob/b47e58a831f8b416601de01833ffc8fc1547acc7/src/test/java/com/vaadin/flow/component/timepicker/tests/TimePickerIT.java#L63)):*
> ```Java
>         executeScript("arguments[0].value = '10:15'", picker);
>         Assert.assertEquals(
>                 "The message should not be shown for the disabled picker", true,
> ```

Last small thing: change this to 
```
Assert.assertEquals("The message should not be shown for the disabled picker", "", message.getText());
```

**Review by ZheSun88 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker-flow/3)* status: 8 of 9 files reviewed, 3 unresolved discussions (waiting on @gilberto-torrezan and @vaadin-bot)

___
*[src/test/java/com/vaadin/flow/component/timepicker/tests/TimePickerIT.java, line 63 at r5](https://reviewable.io/reviews/vaadin/vaadin-time-picker-flow/3#-LIo9AXxBoeZi2DniQHs:-LIoAwTe7MojBPwpHugo:bhswupz) ([raw file](https://github.com/vaadin/vaadin-time-picker-flow/blob/b47e58a831f8b416601de01833ffc8fc1547acc7/src/test/java/com/vaadin/flow/component/timepicker/tests/TimePickerIT.java#L63)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Last small thing: change this to 
```
Assert.assertEquals("The message should not be shown for the disabled picker", "", message.getText());
```
</blockquote></details>

last Done

**Review by gilberto-torrezan — APPROVED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker-flow/3)* status: all files reviewed, 2 unresolved discussions (waiting on @vaadin-bot)

**Review by gilberto-torrezan — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker-flow/3#-:-LIoBpkY0p8wexohVNS2:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @vaadin-bot)

**Review by ZheSun88 — COMMENTED** [review]
> Dismissed @vaadin-bot from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker-flow/3)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
