### PR TITLE
Implement setMin and setMax api (#4)

### LINKED ISSUE #4: Add APIs for setMin and setMax
related ticket 
https://github.com/vaadin/vaadin-time-picker/issues/47

### PR DESCRIPTION
**Pull request by sahalsaad**
Fixes #4 

Added setMin and setMax function to the TimePicker

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker-flow/13)

### CODE REVIEW

**Comment by sahalsaad** [comment]
Will add test when the other PR is merged to master

**Review by bogdanudrescu — COMMENTED** [review]
@sahalsaad 
Could you please fix the conflicts so we may proceed further. The project was restructured since this PR.

Also, what do you mean by 
> the other PR 
?

> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker-flow/13#-:-LXOsDwO8JIMvxiZ3Qdd:bgbp2r5)* status: 0 of 3 files reviewed, all discussions resolved

**Comment by sahalsaad** [comment]
The other PR still in the feature branch. https://github.com/vaadin/vaadin-time-picker/issues/47 haven't closed yet.

**Review by bogdanudrescu — CHANGES_REQUESTED** [review]
Integration Test for new min/max API is missing. I tried the demo and it doesn't seem to work, so I wonder where the problem is. I can still select a time outside of the [min...max] range.


Also the new line used in these files is CRLF instead of only LF, thus in some diff compare tools the whole file looks like it was changed.

> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker-flow/13#-:-LXSwmx_D17NGY6kaUVh:ba6vfhn)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @vaadin-bot)

**Review by bogdanudrescu — COMMENTED** [review]
Also could you please add a label in the demo and update it with the time change as all other demos are doing.

> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker-flow/13#-:-LXT4SKbC5-sEc0C88CR:b-uijy9c)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @vaadin-bot)

**Review by bogdanudrescu — CHANGES_REQUESTED** [review]
OK, I think we nailed the main problem. Could you please change the version of time-picker web component to 1.2.0. It's in vaadin-time-picker-flow/pom.xml.
```
        <dependency>
            <groupId>org.webjars.bowergithub.vaadin</groupId>
            <artifactId>vaadin-time-picker</artifactId>
            <version>1.2.0</version>
        </dependency>
```

> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker-flow/13#-:-LXT6gLHDYjCUiDy8_Ow:bbgrz5c)* status: 0 of 3 files reviewed, 6 unresolved discussions (waiting on @sahalsaad and @vaadin-bot)

___
*[vaadin-time-picker-flow-demo/src/main/java/com/vaadin/flow/component/timepicker/demo/TimePickerView.java, line 173 at r1](https://reviewable.io/reviews/vaadin/vaadin-time-picker-flow/13#-LXT7Pz3C8BeVh5S0sOn:-LXT7Pz3C8BeVh5S0sOo:b-2akhng) ([raw file](https://github.com/vaadin/vaadin-time-picker-flow/blob/b84a60e15d98c7cc716324ede44ecb9e2df928a7/vaadin-time-picker-flow-demo/src/main/java/com/vaadin/flow/component/timepicker/demo/TimePickerView.java#L173)):*
> ```Java
>         timePicker.setMin("05:00");
>         // end-source-example
> ```

Please add a label an update it with the user selection.

**Review by bogdanudrescu — COMMENTED** [review]
Then what happens if the developer sets a value outside the range using timePicker.setValue("01:00")? This case also needs to be in a Unit Test at least.

> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker-flow/13#-:-LXTAQCIEV6_4m9oLuBt:b4zece4)* status: 0 of 3 files reviewed, 6 unresolved discussions (waiting on @sahalsaad and @vaadin-bot)

**Comment by sahalsaad** [comment]
> Then what happens if the developer sets a value outside the range using timePicker.setValue("01:00")? This case also needs to be in a Unit Test at least.
> 
> > _[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker-flow/13#-:-LXTAQCIEV6_4m9oLuBt:b4zece4)_ status: 0 of 3 files reviewed, 6 unresolved discussions (waiting on @sahalsaad and @vaadin-bot)

What should happen when developer do this ?

**Review by bogdanudrescu — CHANGES_REQUESTED** [review]
> What should happen when developer do this ?

`setValue(invalidTime)` should throw an `IllegalArgumentException`. See `AbstractSinglePropertyField.RAW_NON_NULL_IDENTITY` as an example where `null` arguments are considered invalid and a `NullPointerException` is thrown.

However, it's not a blocker. We can add the validation in another one. We may create another ticket for that eventually.

> Reviewed 5 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker-flow/13#-:-LXY4WSq1YjX_2yoOdI_:b-puqym9)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @bogdanudrescu and @sahalsaad)

___
*[vaadin-time-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/timepicker/tests/TimePickerIT.java, line 100 at r2](https://reviewable.io/reviews/vaadin/vaadin-time-picker-flow/13#-LXY5lLX4NDlOpWJi0Pg:-LXY5lLX4NDlOpWJi0Ph:b-rscc85) ([raw file](https://github.com/vaadin/vaadin-time-picker-flow/blob/78defafbace19c4df9568899ccf2da50c1b287ac/vaadin-time-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/timepicker/tests/TimePickerIT.java#L100)):*
> ```Java
> 
>     @Test
>     public void TimePickerWithMinAndMaxSetting() {
> ```

Method should start with lowercase. The above method name has the same issue, could we correct them both please?

**Comment by sahalsaad** [comment]
___
*[vaadin-time-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/timepicker/tests/TimePickerIT.java, line 100 at r2](https://reviewable.io/reviews/vaadin/vaadin-time-picker-flow/13#-LXY5lLX4NDlOpWJi0Pg:-LXZQLCe-uj4V15vhPgw:b-896fix) ([raw file](https://github.com/vaadin/vaadin-time-picker-flow/blob/78defafbace19c4df9568899ccf2da50c1b287ac/vaadin-time-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/timepicker/tests/TimePickerIT.java#L100)):*
<details><summary><i>Previously, bogdanudrescu (Bogdan Udrescu) wrote…</i></summary><blockquote>

Method should start with lowercase. The above method name has the same issue, could we correct them both please?
</blockquote></details>

Done.

**Review by bogdanudrescu — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker-flow/13#-:-LXcMdlD5HbQrIyq0nA3:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
