### PR TITLE
Step API and milliseconds support

### PR DESCRIPTION
**Pull request by pleku**
Do not squash when merging.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker-flow/7)

### CODE REVIEW

**Review by caalador — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker-flow/7)* status: all files reviewed, 4 unresolved discussions (waiting on @vaadin-bot and @pleku)

___
*[src/main/java/com/vaadin/flow/component/timepicker/TimePicker.java, line 20 at r2](https://reviewable.io/reviews/vaadin/vaadin-time-picker-flow/7#-LR5rkh6m452T4vsOjIx-r2-20:-LRBDKGYD4AtYwN1f1K2:bbij4h4) ([raw file](https://github.com/vaadin/vaadin-time-picker-flow/blob/b8d520a8c3ab1df06b91ed8210c4ceea4ced12ce/src/main/java/com/vaadin/flow/component/timepicker/TimePicker.java#L20)):*
<details><summary><i>Previously, vaadin-bot (Vaadin Bot) wrote…</i></summary><blockquote>

MINOR Remove this unused import 'java.time.temporal.ChronoField'. [rule](https://sonar.projects.vaadin.com/coding_rules#rule_key=squid%3AUselessImportCheck)
</blockquote></details>

Please clean imports.
___
*[src/main/java/com/vaadin/flow/component/timepicker/TimePicker.java, line 211 at r2](https://reviewable.io/reviews/vaadin/vaadin-time-picker-flow/7#-LRBEMV6-e7v4zLfQgyP:-LRBEMV6-e7v4zLfQgyQ:b-iivow5) ([raw file](https://github.com/vaadin/vaadin-time-picker-flow/blob/b8d520a8c3ab1df06b91ed8210c4ceea4ced12ce/src/main/java/com/vaadin/flow/component/timepicker/TimePicker.java#L211)):*
> ```Java
>      * @param step
>      *            the step to set, not {@code null} and should divide a day or
>      *            an hour evenly
> ```

Could we validate that set step does divide the day/hour evenly?
Also test that faulty value fails eagerly.

**Review by pleku — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker-flow/7)* status: all files reviewed, 4 unresolved discussions (waiting on @vaadin-bot and @caalador)

___
*[src/main/java/com/vaadin/flow/component/timepicker/TimePicker.java, line 211 at r2](https://reviewable.io/reviews/vaadin/vaadin-time-picker-flow/7#-LRBEMV6-e7v4zLfQgyP:-LRBGGzh2wWzbI8aHtr2:brz3zk8) ([raw file](https://github.com/vaadin/vaadin-time-picker-flow/blob/b8d520a8c3ab1df06b91ed8210c4ceea4ced12ce/src/main/java/com/vaadin/flow/component/timepicker/TimePicker.java#L211)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Could we validate that set step does divide the day/hour evenly?
Also test that faulty value fails eagerly.
</blockquote></details>

Good idea, I'll add server side verification for the given value, and also just unit test for setter  & getter matching.

BTW. dividing of step is broken in web component https://github.com/vaadin/vaadin-time-picker/issues/79

**Review by pleku — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker-flow/7)* status: 5 of 7 files reviewed, 4 unresolved discussions (waiting on @caalador and @vaadin-bot)

___
*[src/main/java/com/vaadin/flow/component/timepicker/TimePicker.java, line 211 at r2](https://reviewable.io/reviews/vaadin/vaadin-time-picker-flow/7#-LRBEMV6-e7v4zLfQgyP:-LRBawkx9iwot79VkgEQ:b-896fix) ([raw file](https://github.com/vaadin/vaadin-time-picker-flow/blob/b8d520a8c3ab1df06b91ed8210c4ceea4ced12ce/src/main/java/com/vaadin/flow/component/timepicker/TimePicker.java#L211)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Good idea, I'll add server side verification for the given value, and also just unit test for setter  & getter matching.

BTW. dividing of step is broken in web component https://github.com/vaadin/vaadin-time-picker/issues/79
</blockquote></details>

Done.

**Review by pleku — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker-flow/7)* status: 5 of 7 files reviewed, 4 unresolved discussions (waiting on @caalador and @vaadin-bot)

___
*[src/main/java/com/vaadin/flow/component/timepicker/TimePicker.java, line 20 at r2](https://reviewable.io/reviews/vaadin/vaadin-time-picker-flow/7#-LR5rkh6m452T4vsOjIx-r2-20:-LRBckP_5MKO0kdDDNYy:bqe68dr) ([raw file](https://github.com/vaadin/vaadin-time-picker-flow/blob/b8d520a8c3ab1df06b91ed8210c4ceea4ced12ce/src/main/java/com/vaadin/flow/component/timepicker/TimePicker.java#L20)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Please clean imports.
</blockquote></details>

Done. (IntelliJ update decided to switch editor rules ...)

**Review by caalador — APPROVED** [review]
java.lang.AssertionError: Errors with Locale Chinese (Singapore)
	at com.vaadin.flow.component.timepicker.tests.TimePickerLocalizationIT.runMillisecondLocalizationTest(TimePickerLocalizationIT.java:329)
	at com.vaadin.flow.component.timepicker.tests.TimePickerLocalizationIT.testMilliseconds_localeWithColonSeparator_inputParsedProperly(TimePickerLocalizationIT.java:82)
------- Stderr: -------
Nov 13, 2018 10:48:21 AM com.vaadin.flow.component.timepicker.tests.TimePickerLocalizationIT runMillisecondLocalizationTest
SEVERE: expected: ??4:05 actual: ??4:05:00
expected: 01:00 actual: 04:05:00
expected: 01:00:00.000 actual: 04:05:00.000
Server value error: expected: 1:0:0.0 actual: 4:5:0.0

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker-flow/7#-:-LRBk7699e2TEkNwb2zL:brg1dt8)* status: all files reviewed, 3 unresolved discussions (waiting on @vaadin-bot)

**Review by caalador — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker-flow/7)* status: all files reviewed, 3 unresolved discussions (waiting on @vaadin-bot)

**Review by caalador — APPROVED** [review]
> Dismissed @vaadin-bot from 3 discussions.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker-flow/7)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
